import * as stylex from "@stylexjs/stylex";
import { color, dark, font, light } from "./tokens.stylex";

/** Pins `color` to one palette when the learner picks a theme explicitly (lib/theme.ts). */
export const lightTheme = stylex.createTheme(color, {
  backdrop: light.backdrop,
  frame: light.frame,
  surface: light.surface,
  surface2: light.surface2,
  surface3: light.surface3,
  border: light.border,
  borderStrong: light.borderStrong,
  text: light.text,
  textMuted: light.textMuted,
  primary: light.primary,
  primaryHover: light.primaryHover,
  onPrimary: light.onPrimary,
  accentText: light.accentText,
  lilac: light.lilac,
  lilacSoft: light.lilacSoft,
  pistachio: light.pistachio,
  pistachioSoft: light.pistachioSoft,
  peach: light.peach,
  peachSoft: light.peachSoft,
  butter: light.butter,
  onLilac: light.onLilac,
  onPistachio: light.onPistachio,
  onButter: light.onButter,
  onPeach: light.onPeach,
  danger: light.danger,
  dangerSoft: light.dangerSoft,
  success: light.success,
  successSoft: light.successSoft,
  warning: light.warning,
  warningSoft: light.warningSoft,
  focus: light.focus,
  chart1: light.chart1,
  chart2: light.chart2,
  chart3: light.chart3,
  chartTrack: light.chartTrack,
  fig1: light.fig1,
  fig2: light.fig2,
  fig3: light.fig3,
  fig4: light.fig4,
  fig5: light.fig5,
  fig6: light.fig6,
  selection: light.selection,
  shadow: light.shadow,
  shadowStrong: light.shadowStrong,
  scrim: light.scrim,
});

export const darkTheme = stylex.createTheme(color, {
  backdrop: dark.backdrop,
  frame: dark.frame,
  surface: dark.surface,
  surface2: dark.surface2,
  surface3: dark.surface3,
  border: dark.border,
  borderStrong: dark.borderStrong,
  text: dark.text,
  textMuted: dark.textMuted,
  primary: dark.primary,
  primaryHover: dark.primaryHover,
  onPrimary: dark.onPrimary,
  accentText: dark.accentText,
  lilac: dark.lilac,
  lilacSoft: dark.lilacSoft,
  pistachio: dark.pistachio,
  pistachioSoft: dark.pistachioSoft,
  peach: dark.peach,
  peachSoft: dark.peachSoft,
  butter: dark.butter,
  onLilac: dark.onLilac,
  onPistachio: dark.onPistachio,
  onButter: dark.onButter,
  onPeach: dark.onPeach,
  danger: dark.danger,
  dangerSoft: dark.dangerSoft,
  success: dark.success,
  successSoft: dark.successSoft,
  warning: dark.warning,
  warningSoft: dark.warningSoft,
  focus: dark.focus,
  chart1: dark.chart1,
  chart2: dark.chart2,
  chart3: dark.chart3,
  chartTrack: dark.chartTrack,
  fig1: dark.fig1,
  fig2: dark.fig2,
  fig3: dark.fig3,
  fig4: dark.fig4,
  fig5: dark.fig5,
  fig6: dark.fig6,
  selection: dark.selection,
  shadow: dark.shadow,
  shadowStrong: dark.shadowStrong,
  scrim: dark.scrim,
});

/**
 * Plain custom properties for CSS that StyleX does not render: markdown prose, mermaid/SVG figure
 * internals, the widget iframe and lib/color.ts. Lesson figures reference var(--fig-1..6).
 */
export const bridge = stylex.create({
  root: {
    "--text": color.text,
    "--text-muted": color.textMuted,
    "--surface": color.surface,
    "--surface-2": color.surface2,
    "--border": color.border,
    "--border-strong": color.borderStrong,
    "--primary": color.primary,
    "--on-primary": color.onPrimary,
    "--accent-text": color.accentText,
    "--focus": color.focus,
    "--danger": color.danger,
    "--success": color.success,
    "--lilac-soft": color.lilacSoft,
    "--peach-soft": color.peachSoft,
    "--pistachio-soft": color.pistachioSoft,
    "--butter": color.butter,
    "--selection": color.selection,
    "--fig-1": color.fig1,
    "--fig-2": color.fig2,
    "--fig-3": color.fig3,
    "--fig-4": color.fig4,
    "--fig-5": color.fig5,
    "--fig-6": color.fig6,
    "--font-display": font.display,
    "--font-body": font.body,
    "--font-mono": font.mono,
  },
});
