import * as stylex from "@stylexjs/stylex";

// "Soft start": cream surfaces on a peach backdrop, eggplant ink, lilac / pistachio / peach / butter pastels.
// `light` and `dark` hold each palette once; `color` is what components use. It follows the OS by
// default, and themes.ts pins it to one palette when the learner picks a theme explicitly.

const DARK = "@media (prefers-color-scheme: dark)";

export const light = stylex.defineVars({
  backdrop: "#FFC2AC",
  frame: "#FCF3EA",
  surface: "#FFF9F3",
  surface2: "#F4EAE0",
  surface3: "#ECDFD2",
  border: "#EADCCD",
  borderStrong: "#857796",
  text: "#32253F",
  textMuted: "#584B66",
  primary: "#32253F",
  primaryHover: "#4A3A5C",
  onPrimary: "#FFF8F0",
  accentText: "#5640AE",
  lilac: "#CBC9F5",
  lilacSoft: "#E7E5FB",
  pistachio: "#D9E9AD",
  pistachioSoft: "#ECF3D5",
  peach: "#FFC9B4",
  peachSoft: "#FFE0D3",
  butter: "#FBE6C4",
  onLilac: "#32253F",
  onPistachio: "#4A7419",
  onButter: "#A2530A",
  onPeach: "#A23F22",
  danger: "#AE3329",
  dangerSoft: "#FCE2DD",
  success: "#3D6B1E",
  successSoft: "#E6F0CD",
  warning: "#865000",
  warningSoft: "#FCEACB",
  focus: "#6B4FD8",
  chart1: "#6B55D0",
  chart2: "#D9693D",
  chart3: "#6A962A",
  chartTrack: "#EEE3D7",
  fig1: "#6B55D0",
  fig2: "#C9592F",
  fig3: "#5A8823",
  fig4: "#2A7896",
  fig5: "#AE4280",
  fig6: "#3E3049",
  selection: "#E7E5FB",
  shadow: "rgb(120 72 48 / 0.10)",
  shadowStrong: "rgb(120 72 48 / 0.18)",
  scrim: "rgb(50 37 63 / 0.35)",
});

export const dark = stylex.defineVars({
  backdrop: "#1B1322",
  frame: "#231A2C",
  surface: "#2C2137",
  surface2: "#362A43",
  surface3: "#41334F",
  border: "#463A55",
  borderStrong: "#8F80A2",
  text: "#F7EEE6",
  textMuted: "#C6B8D2",
  primary: "#CBC9F5",
  primaryHover: "#DFDDFA",
  onPrimary: "#251B30",
  accentText: "#C4BCFF",
  lilac: "#3A335F",
  lilacSoft: "#342C4C",
  pistachio: "#33402A",
  pistachioSoft: "#2F3927",
  peach: "#4A2F2E",
  peachSoft: "#44302F",
  butter: "#45382A",
  onLilac: "#D9D6FF",
  onPistachio: "#BADD8B",
  onButter: "#F6CA84",
  onPeach: "#FFB8A2",
  danger: "#FF9F93",
  dangerSoft: "#4A2A31",
  success: "#B6DA86",
  successSoft: "#2F3B27",
  warning: "#F6C980",
  warningSoft: "#43372B",
  focus: "#B6A8FF",
  chart1: "#A99BFF",
  chart2: "#F4A27F",
  chart3: "#A9CF6C",
  chartTrack: "#3B2F48",
  fig1: "#A99BFF",
  fig2: "#F29C76",
  fig3: "#A3CC66",
  fig4: "#73C0DD",
  fig5: "#E88BC0",
  fig6: "#EDE3F5",
  selection: "#4A3F6B",
  shadow: "rgb(0 0 0 / 0.28)",
  shadowStrong: "rgb(0 0 0 / 0.4)",
  scrim: "rgb(10 6 14 / 0.6)",
});

export const color = stylex.defineVars({
  backdrop: { default: light.backdrop, [DARK]: dark.backdrop },
  frame: { default: light.frame, [DARK]: dark.frame },
  surface: { default: light.surface, [DARK]: dark.surface },
  surface2: { default: light.surface2, [DARK]: dark.surface2 },
  surface3: { default: light.surface3, [DARK]: dark.surface3 },
  border: { default: light.border, [DARK]: dark.border },
  borderStrong: { default: light.borderStrong, [DARK]: dark.borderStrong },
  text: { default: light.text, [DARK]: dark.text },
  textMuted: { default: light.textMuted, [DARK]: dark.textMuted },
  primary: { default: light.primary, [DARK]: dark.primary },
  primaryHover: { default: light.primaryHover, [DARK]: dark.primaryHover },
  onPrimary: { default: light.onPrimary, [DARK]: dark.onPrimary },
  accentText: { default: light.accentText, [DARK]: dark.accentText },
  lilac: { default: light.lilac, [DARK]: dark.lilac },
  lilacSoft: { default: light.lilacSoft, [DARK]: dark.lilacSoft },
  pistachio: { default: light.pistachio, [DARK]: dark.pistachio },
  pistachioSoft: { default: light.pistachioSoft, [DARK]: dark.pistachioSoft },
  peach: { default: light.peach, [DARK]: dark.peach },
  peachSoft: { default: light.peachSoft, [DARK]: dark.peachSoft },
  butter: { default: light.butter, [DARK]: dark.butter },
  onLilac: { default: light.onLilac, [DARK]: dark.onLilac },
  onPistachio: { default: light.onPistachio, [DARK]: dark.onPistachio },
  onButter: { default: light.onButter, [DARK]: dark.onButter },
  onPeach: { default: light.onPeach, [DARK]: dark.onPeach },
  danger: { default: light.danger, [DARK]: dark.danger },
  dangerSoft: { default: light.dangerSoft, [DARK]: dark.dangerSoft },
  success: { default: light.success, [DARK]: dark.success },
  successSoft: { default: light.successSoft, [DARK]: dark.successSoft },
  warning: { default: light.warning, [DARK]: dark.warning },
  warningSoft: { default: light.warningSoft, [DARK]: dark.warningSoft },
  focus: { default: light.focus, [DARK]: dark.focus },
  chart1: { default: light.chart1, [DARK]: dark.chart1 },
  chart2: { default: light.chart2, [DARK]: dark.chart2 },
  chart3: { default: light.chart3, [DARK]: dark.chart3 },
  chartTrack: { default: light.chartTrack, [DARK]: dark.chartTrack },
  fig1: { default: light.fig1, [DARK]: dark.fig1 },
  fig2: { default: light.fig2, [DARK]: dark.fig2 },
  fig3: { default: light.fig3, [DARK]: dark.fig3 },
  fig4: { default: light.fig4, [DARK]: dark.fig4 },
  fig5: { default: light.fig5, [DARK]: dark.fig5 },
  fig6: { default: light.fig6, [DARK]: dark.fig6 },
  selection: { default: light.selection, [DARK]: dark.selection },
  shadow: { default: light.shadow, [DARK]: dark.shadow },
  shadowStrong: { default: light.shadowStrong, [DARK]: dark.shadowStrong },
  scrim: { default: light.scrim, [DARK]: dark.scrim },
});

export const space = stylex.defineVars({
  xxs: "4px",
  xs: "6px",
  sm: "8px",
  md: "12px",
  lg: "16px",
  xl: "24px",
  xxl: "32px",
});

export const font = stylex.defineConsts({
  display: '"Rubik", "Onest", ui-sans-serif, system-ui, sans-serif',
  body: '"Onest", ui-sans-serif, system-ui, sans-serif',
  mono: 'ui-monospace, "SF Mono", Menlo, monospace',
});

/** The learner's reading preferences: styles/global.css sets these properties from lib/reading.ts. Sizes are `calc(<px> * scale)`. */
export const reading = stylex.defineConsts({
  font: "var(--reading-font)",
  scale: "var(--reading-scale)",
  leading: "var(--reading-leading)",
  measure: "var(--reading-measure)",
});

export const radius = stylex.defineConsts({
  frame: "40px",
  card: "28px",
  inner: "20px",
  field: "16px",
  small: "12px",
  pill: "999px",
});

export const bp = stylex.defineConsts({
  wide: "@media (max-width: 1280px)",
  tablet: "@media (max-width: 1100px)",
  mobile: "@media (max-width: 900px)",
  phone: "@media (max-width: 480px)",
  reduce: "@media (prefers-reduced-motion: reduce)",
});

export const motion = stylex.defineConsts({
  ease: "cubic-bezier(0.16, 1, 0.3, 1)",
  fast: "160ms",
  base: "220ms",
});
